version: '3.9'

services:
  api:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/app
    environment:
      - ENV=dev
    env_file:
      - .env

  test:
    build: .
    command: sh -c "PYTHONPATH=/app pytest tests/"
    volumes:
      - .:/app
    working_dir: /app